name: Build on Windows and MacOS

on:
  release:
    types:
      - published

jobs:
  build-wheel-win-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: |
        # test your matrix by printing the current Python version
        python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt

    - name: Lint with flake8 for sysntax errors
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build Python wheels on ${{ matrix.os }} py${{ matrix.python-version }}
      run: python setup.py bdist_wheel

    - name: List the *.whl packages
      run: ls dist/*.whl

#    - name: Publish wheels to PyPI
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#      run: twine upload dist/*.whl

#    - name: Get Latest Release
#      id: latest_release
#      uses: jossef/action-latest-release-info@v1.2.2
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload whl package
      uses: actions/upload-release-asset@v1
      with:
#        upload_url: ${{ steps.latest_release.outputs.upload_url }}
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/latest/assets
        asset_path: /dist/*.whl
        # asset_name: package.whl
        asset_content_type: application/zip
        file_glob: true
